### PR TITLE
[JS] Trigger release 0.9.1

### PR DESCRIPTION
**Pull request by wkal-pubnub**
feat: Lock moderated messages from editing

### CODE REVIEW

**Comment by wkal-pubnub** [comment]
@pubnub-release-bot release js as 0.9.1

**Comment by wkal-pubnub** [comment]
@pubnub-release-bot release js as 0.9.1

**Comment by wkal-pubnub** [comment]
@pubnub-release-bot release js as 0.9.1

**Review by marcin-cebo — APPROVED** [review]

**Comment by wkal-pubnub** [comment]
@pubnub-release-bot release js as 0.9.0-dev

**Pull request merged**
